# Generated by Django 6.1.1 on 2026-09-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('corporate', 'وب\u200cسایت شرکتی'), ('store', 'فروشگاه اینترنتی'), ('personal', 'وب\u200cسایت شخصی'), ('portfolio', 'وب\u200cسایت نمونه\u200cکار'), ('blog', 'وب\u200cسایت وبلاگی'), ('landing', 'لندینگ پیج'), ('educational', 'وب\u200cسایت آموزشی'), ('booking', 'سیستم رزرو و نوبت\u200cدهی'), ('dashboard', 'پنل مدیریت'), ('web_app', 'اپلیکیشن تحت وب'), ('custom', 'پروژه اختصاصی'), ('other', 'سایر')], max_length=30, verbose_name='نوع پروژه')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سفارش')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
