# Generated by Django 6.1.1 on 2026-09-26 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('url_title', models.SlugField(max_length=200, unique=True, verbose_name='عنوان در URL')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='تصویر اصلی پروژه')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع پروژه')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان پروژه')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('github_url', models.URLField(blank=True, verbose_name='آدرس گیت\u200cهاب')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مهارت')),
                ('url_title', models.SlugField(max_length=100, unique=True, verbose_name='عنوان در URL')),
                ('image', models.ImageField(upload_to='skills/', verbose_name='تصویر مهارت')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProjectChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.TextField(verbose_name='چالش')),
                ('solution', models.TextField(verbose_name='راه\u200cحل')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='projects_module.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'چالش پروژه',
                'verbose_name_plural': 'چالش\u200cهای پروژه',
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان قابلیت')),
                ('icon_name', models.CharField(max_length=200, verbose_name='نام آیکون')),
                ('description', models.TextField(verbose_name='توضیحات قابلیت')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='projects_module.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'قابلیت پروژه',
                'verbose_name_plural': 'قابلیت\u200cهای پروژه',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='تصویر')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان تصویر')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects_module.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تصویر پروژه',
                'verbose_name_plural': 'گالری تصاویر پروژه',
            },
        ),
    ]
