# Generated by Django 6.1.1 on 2026-09-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects_module.skill', verbose_name='تکنولوژی\u200cها'),
        ),
    ]
