# Generated by Django 6.1.1 on 2026-09-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_module', '0002_project_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='url_title',
        ),
    ]
