# Generated by Django 6.1.1 on 2026-09-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_module', '0003_remove_skill_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.FileField(upload_to='skills/', verbose_name='تصویر مهارت'),
        ),
    ]
