# Generated by Django 6.1.1 on 2026-09-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_module', '0004_alter_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url_title',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='عنوان در URL'),
        ),
    ]
