# Generated by Django 6.1.1 on 2026-09-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_module', '0006_project_is_active_skill_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='ability_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='امتیاز'),
        ),
    ]
