# Generated by Django 6.1.1 on 2026-09-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('domain', models.URLField(verbose_name='دامنه سایت')),
                ('developer_name', models.CharField(max_length=100, verbose_name='نام سازنده')),
                ('about_developer', models.TextField(verbose_name='درباره سازنده')),
                ('github_url', models.URLField(blank=True, verbose_name='آدرس گیت\u200cهاب')),
                ('instagram_url', models.URLField(blank=True, verbose_name='آدرس اینستاگرام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('completed_projects', models.PositiveIntegerField(default=0, verbose_name='تعداد پروژه\u200cهای انجام شده')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='سال تجربه')),
                ('logo', models.FileField(blank=True, null=True, upload_to='site/', verbose_name='لوگوی سایت')),
            ],
            options={
                'verbose_name': 'اطلاعات سایت',
                'verbose_name_plural': 'اطلاعات سایت',
            },
        ),
    ]
