# Generated by Django 6.1.1 on 2026-09-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_public_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='short_description_developer',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
    ]
