# Generated by Django 6.1.1 on 2026-09-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_public_short_description_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان لینک')),
                ('url', models.CharField(max_length=255, verbose_name='آدرس لینک')),
                ('link_type', models.CharField(choices=[('quick', 'لینک سریع'), ('site', 'لینک سایت')], max_length=20, verbose_name='نوع لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینک\u200cهای فوتر',
            },
        ),
        migrations.AddField(
            model_name='public',
            name='copy_right',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='متن گپی رایت'),
        ),
    ]
